"""1

Revision ID: 74bad301daae
Revises: 
Create Date: 2023-04-06 19:46:25.827022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4264b4b8e3c1'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacja', sa.String(length=20), nullable=False),
    sa.Column('nazwakwota', sa.String(length=50), nullable=False),
    sa.Column('cena', sa.String(length=20), nullable=False),
    sa.Column('ilosc', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mag',
    sa.Column('idx', sa.String(length=60), nullable=False),
    sa.Column('nazwa', sa.String(length=50), nullable=False),
    sa.Column('cena', sa.String(length=20), nullable=False),
    sa.Column('ilosc', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('saldo',
    sa.Column('saldo', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('saldo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldo')
    op.drop_table('mag')
    op.drop_table('log')
    # ### end Alembic commands ###
